### ISSUE TITLE
Failed to download dataset from FF++ 

### ISSUE THREAD

**Issue by KwunTangKwai** [megvii-research/CADDM#12]
My supervisor have done the procedure to receive the downloading script from the FF++ authors. However, upon running the script, my device failed to gain connection with the download server. I tried accessing the server link directly and it shows "site cannot be reached. What should I do to continue? Thank you.

**Comment by KwunTangKwai** [comment]
script output:
Downloading videos of dataset "original_sequences/youtube"
Traceback (most recent call last):
  File "/home/sean/anaconda3/envs/king/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/sean/anaconda3/envs/king/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/sean/anaconda3/envs/king/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/sean/anaconda3/envs/king/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/sean/anaconda3/envs/king/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/sean/anaconda3/envs/king/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/home/sean/anaconda3/envs/king/lib/python3.11/http/client.py", line 942, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/anaconda3/envs/king/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/home/sean/anaconda3/envs/king/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sean/Desktop/King/CADDM-master/download-Faceforensics.py", line 261, in <module>
    main(args)
  File "/home/sean/Desktop/King/CADDM-master/download-Faceforensics.py", line 188, in main
    file_pairs = json.loads(urllib.request.urlopen(args.base_url + '/' +
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/anaconda3/envs/king/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/anaconda3/envs/king/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/anaconda3/envs/king/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/anaconda3/envs/king/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/sean/anaconda3/envs/king/lib/python3.11/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/anaconda3/envs/king/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
