### ISSUE TITLE
KeyError: './train_images/manipulated_sequences/Deepfakes/raw/frames/585_599/frame_0

### ISSUE THREAD

**Issue by Sun-researcher** [megvii-research/CADDM#34]
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    train()
  File "train.py", line 102, in train
    train_dataset = DeepfakeDataset('train', cfg)
  File "/home/lab/tSun/CADDM-master/dataset.py", line 37, in __init__
    self.samples = self.collect_samples()
  File "/home/lab/tSun/CADDM-master/dataset.py", line 56, in collect_samples
    info_meta = self.info_meta_dict[info_key]    
KeyError: './train_images/manipulated_sequences/Deepfakes/raw/frames/585_599/frame_0'

I ran into this problem while running the program. Can you help me solve it!

**Comment by Ding-yd** [comment]
你可以看一下你的训练集json文件的路径问题

**Comment by Ding-yd** [comment]
我的是在使用test.py时出现的相同问题，这是因为在使用extract...py 处理数据集时所生成的json文件中的许多图片，其实在train_images或者test_images的图片文件夹之下并不存在

**Comment by Sun-researcher** [comment]
那兄弟该怎么办

**Comment by Ding-yd** [comment]
没想出好的解决方法，就把提取的frame对应的source_img都设置成original中的frame_0

**Comment by Sun-researcher** [comment]
/train_images/manipulated_sequences/NeuralTextures/c23/frames\\001_870/frame_357
在ldm.json文件把"\\"改为“/”就可以识别图片，当时我不知道出错的程序在哪

**Comment by Usriscedjdj** [comment]
![image](https://github.com/megvii-research/CADDM/assets/96629668/b0a5ae69-8543-4700-8801-b7bc7e8b16c2)
请问我这个问题是因为json文件有问题吗？

**Comment by Sun-researcher** [comment]
应该不是吧，我也遇见这个问题

**Comment by Usriscedjdj** [comment]
老兄有没有跑通，可否加个vx交流一下？
2963780474@qq.com,这是邮箱
